# Adapted from: https://github.com/guinp1n/docker-compose-hivemq-ce
version: "1.0"
services:
  hivemq:
    image: hivemq/hivemq-ce  # hivemq/hivemq4:latest
    container_name: hivemq-broker
    environment:
      - HIVEMQ_LOG_LEVEL=DEBUG
    ports:
      - "1883:1883"
      - "8080:8080"
      - "9399:9399"
    volumes:
      - ./config/hive-config.xml:/opt/hivemq/conf/config.xml
      - ./hivemq-prometheus-extension:/opt/hivemq/extensions/hivemq-prometheus-extension
    networks:
      - hivemq_net
  prometheus:
    container_name: prometheus-ce
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    healthcheck:
        test: "wget --no-verbose --tries=1 --spider localhost:9090 || exit 1"
        start_period: 5s
        interval: 30s
        timeout: 10s
        retries: 5
    depends_on:
      - "hivemq"
    networks:
      - hivemq_net
  grafana:
    container_name: grafana-ce
    image: grafana/grafana
    depends_on:
      - "prometheus"
    ports:
      - 3000:3000
    networks:
      - hivemq_net
  publiser:
    image: publisher
    container_name: publisher-ce
    volumes:
      - ./config/publisher.yml:/etc/publisher/config.yaml
      - ./publisher/data:/data   
    depends_on:
      - "data-validation"
    networks:
      - hivemq_net
  data-validation:
    image: data_instrumentation
    container_name: data-validation-ce
    ports:
      - "9091:9091"
    volumes:
      - ./config/data_instrumentation.yml:/etc/data_instrumentation/config.yaml    
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - hivemq_net
networks:
  hivemq_net:
    
